name: Tag and release

on:
  workflow_dispatch:
  push:
    branches: ["main"]

permissions:
  contents: write
  packages: write

jobs:
  tag-and-release-lfs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 99
      - uses: paulhatch/semantic-version@v5.0.2
        id: get-next-semantic-version
        with:
          tag_prefix: "v"
          version_format: "v${major}.${minor}.${patch}"
          bump_each_commit: true
      - name: Create tag
        uses: actions/github-script@v6
        with:
          script: |
            const owner = "${{ github.repository_owner }}";
            const repo = "${{ github.repository }}".split('/')[1];
            const version = "${{ steps.get-next-semantic-version.outputs.version }}";
            const sha = "${{ github.sha }}";

            const tag = await github.rest.git.createTag({
              owner: owner,
              repo: repo,
              tag: version,
              message: `Release for ${version}`,
              object: sha,
              type: "commit",
              tagger: {
                name: "Jasmina Vasiljevic",
                email: "jvasiljevic@tenstorrent.com",
              }
            });
            github.rest.git.createRef({
              owner: owner,
              repo: repo,
              ref: `refs/tags/${version}`,
              sha: tag.data.sha,
            });
      - name: Create VERSION
        run: echo ${{ steps.get-next-semantic-version.version }} > VERSION
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: VERSION
